apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    name:  user-api
spec:
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - image: vinitkulkarni/user-api
        name: user-api
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        ports:
        - containerPort: 1025
          name: http
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: user-api-secrets
                key: connectionstring
          - name: PORT
            value: "1025"
          - name: ADMIN_EMAIL
            value: vinitkkulkarni@gmail.com
