kind: Deployment
metadata:
  name: admin-api
  labels:
    name:  admin-api
spec:
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
      - image: vinitkulkarni/admin-api
        name: admin-api
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        ports:
        - containerPort: 1025
          name: http
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: admin-api-secrets
                key: connectionstring
          - name: PORT
            value: "1025"
