apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
  labels:
    app: user-ui
spec:
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
    spec:
      volumes:
        - name: user-ui-vl
          configMap:
            name: user-ui-cm
      containers:
      - image: vinitkulkarni/user-ui
        name: user-ui
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
          - name: user-ui-vl
            mountPath: /app/.env
            subPath: .env
